
apiVersion: v1
kind: Service
metadata:
  name: peer0-org2-hlf-k8s-com
  namespace: hlfk8s
spec:
  type: ClusterIP
  selector:
    component: "peer0.org2.hlf.k8s.com"
  ports:
  - name: "grpcs"
    port: 7051
    protocol: TCP
    targetPort: 7051
  - name: "chaincode-listen-address"
    port: 7052
    protocol: TCP
    targetPort: 7052
