
apiVersion: v1
kind: Service
metadata:
  name: chaincode-as-external-service
  namespace: hlfk8s
spec:
  type: ClusterIP
  selector:
    chaincode: chaincode-demo
  ports:
  - name: "grpcs"
    port: 9999
    protocol: TCP
    targetPort: 9999
