OrdererOrgs:
  - Name: Orderer
    Domain: hlf.k8s.com
    EnableNodeOUs: true
    Specs:
      - Hostname: orderer0
        SANS:
          - localhost
          - orderer0.hlf.k8s.com
      - Hostname: orderer1
        SANS:
          - localhost
          - orderer1.hlf.k8s.com
      - Hostname: orderer2
        SANS:
          - localhost
          - orderer2.hlf.k8s.com
PeerOrgs:
  - Name: Org1
    Domain: org1.hlf.k8s.com
    EnableNodeOUs: true
    Template:
      Count: 1
      SANS:
        - localhost
        - "{{.Hostname}}.hlf.k8s.com"
    Users:
      Count: 1
  - Name: Org2
    Domain: org2.hlf.k8s.com
    EnableNodeOUs: true
    Template:
      Count: 1
      SANS:
        - localhost
        - "{{.Hostname}}.hlf.k8s.com"
    Users:
      Count: 1
  - Name: Org3
    Domain: org3.hlf.k8s.com
    EnableNodeOUs: true
    Template:
      Count: 1
      SANS:
        - localhost
        - "{{.Hostname}}.hlf.k8s.com"
    Users:
      Count: 1
