
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "couchdb.hlf.k8s.com"
  namespace: hlfk8s
  labels:
    component: "couchdb.hlf.k8s.com"
spec:
  replicas: 1
  selector:
    matchLabels:
      component: "couchdb.hlf.k8s.com"
  template:
    metadata:
      labels:
        component: "couchdb.hlf.k8s.com"
    spec:
      containers:
        - name: couchdb-hlf-k8s-com
          image: couchdb:3.2.2
          env:
            - name: COUCHDB_USER
              valueFrom:
                secretKeyRef:
                  name: couchdb
                  key: username
            - name: COUCHDB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: couchdb
                  key: password
          ports:
            - containerPort: 5984
          livenessProbe:
            httpGet:
              path: /
              port: 5984
            initialDelaySeconds: 5
            failureThreshold: 5
            periodSeconds: 1
