
apiVersion: v1
kind: Service
metadata:
  name: couchdb-org1-hlf-k8s-com
  namespace: hlfk8s
spec:
  type: ClusterIP
  selector:
    component: "couchdb.org1.hlf.k8s.com"
  ports:
  - name: "couchdb"
    port: 5984
    protocol: TCP
    targetPort: 5984
