apiVersion: apps/v1
kind: Deployment
metadata:
  name: "cli.peer0.org2.hlf.k8s"
  namespace: hlfk8s
  labels:
    component: "cli.peer0.org2.hlf.k8s"
spec:
  replicas: 1
  selector:
    matchLabels:
      component: "cli.peer0.org2.hlf.k8s"
  template:
    metadata:
      labels:
        component: "cli.peer0.org2.hlf.k8s"
    spec:
      containers:
        - name: cli-peer0-org2-hlf-k8s-com
          image: hyperledger/fabric-tools:2.4
          imagePullPolicy: IfNotPresent
          workingDir: /etc/hyperledger/fabric/
          tty: true
          stdin: true
          env:
            - name: FABRIC_LOGGING_SPEC
              value: info
            - name: CHANNEL_NAME
              value: channelall
            - name: CORE_PEER_ADDRESS
              value: peer0.org2.hlf.k8s.com
            - name: CORE_PEER_LOCALMSPID
              value: Org2MSP
            - name: CORE_PEER_TLS_ENABLED
              value: "true"
            - name: CORE_PEER_TLS_ROOTCERT_FILE
              value: /etc/hyperledger/fabric/crypto/peerOrganizations/org2.hlf.k8s/peers/peer0.org2.hlf.k8s/tls/ca.crt
            - name: CORE_PEER_MSPCONFIGPATH
              value: /etc/hyperledger/fabric/crypto/peerOrganizations/org2.hlf.k8s/users/Admin@org2.hlf.k8s/msp
            - name: ORDERER_CA
              value: /etc/hyperledger/fabric/crypto/ordererOrganizations/hlf.k8s/orderers/orderer0.hlf.k8s/msp/tlscacerts/tlsca.hlf.k8s-cert.pem
          volumeMounts:
            - name: chaincode-package
              mountPath: /etc/hyperledger/fabric/chaincodes
            - name: hlf-artifacts
              mountPath: /etc/hyperledger/fabric/artifacts
            - name: hlf-crypto-config
              mountPath: /etc/hyperledger/fabric/crypto
      volumes:
        - name: chaincode-package
          persistentVolumeClaim:
            claimName: chaincode-package
        - name: hlf-artifacts
          persistentVolumeClaim:
            claimName: hlf-artifacts
        - name: hlf-crypto-config
          persistentVolumeClaim:
            claimName: hlf-crypto-config
